filebeat.inputs:
- type: log
  enabled: true
  paths:
    - {{ LOG_FILE }}
  reload.enabled: false
  fields:
    component: {{ COMPONENT }}
output.logstash:
  hosts: ["172.31.17.239:5044"]

## Defaults
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
