- name: Update Logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Check logstash Running or not
  ansible.builtin.shell: sleep 30 ; netstat -lntp | grep 5044



