- name: Add RoboShop Application User
  when: APP_USER is defined
  ansible.builtin.user:
    name: "{{ APP_USER }}"
  register: appuser

- name: Remove Previous Version of App
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

### Since we are moving to nexus to download artifacts we commented this
#- name: Download App Content & Extract it
#  ansible.builtin.unarchive:
#    src: https://github.com/raghudevopsb69/{{COMPONENT}}/archive/refs/heads/main.zip
#    dest: "/tmp"
#    remote_src: yes
#
#- name: Copy Extracted App Content to App Location
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: "{{ APP_LOC }}/"
#    remote_src: yes

- name: Create App Location
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: directory

- name: Download App Content & Extract it
  ansible.builtin.unarchive:
    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.devopsb69.online:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{ APP_LOC }}"
    remote_src: yes


