- name: Copy MongoDB YUM repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: "{{ lookup('aws_ssm', 'param.{{ENV}}.catalogue.MONGO_ENDPOINT', region='us-east-1' ) }}"
#    file: "{{APP_LOC}}/schema/{{COMPONENT}}.js"
#    #idempotent: yes
#  ignore_errors: true

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host {{ lookup('aws_ssm', 'param.{{ENV}}.{{COMPONENT}}.MONGO_ENDPOINT', region='us-east-1' ) }}:27017 --sslCAFile rds-combined-ca-bundle.pem --username admin1 --password RoboShop123 <schema/{{SCHEMA_NAME}}.js
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  ignore_errors: true
