- name: Setup SystemD service file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Copy RSyslog Config
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart Rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted


