route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: raghudevopsb69@gmail.com
        from: raghudevopsb69@gmail.com
        smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: {{SES_USR}}
        auth_password: {{SES_PSW}}
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
